### ISSUE TITLE
关于添加自动回复的小建议

### ISSUE THREAD

**Issue by Ghost826** [Kloping/Mirai_Plugins_Auto_Reply#1]
开发者你好，由于在群聊中人数比较多，所以每次发送完指令之后，还没等添加回复语句，就有可能被别人随便发的一句话给“截胡”，不知道我这样描述你能不能听懂。
所以我想提一个小建议，就是只用一个语句，就完成自动回复语句的添加。例如下面这句：
hf 你好 你好啊
以上的三个字符串，每个字符串之间用空格隔开，这样就能只发送一个语句就能完成添加。
并没有说你现在开发的哪里不好，只是感觉如果用这种方式，更加简单，快捷。

**Comment by Kloping** [comment]
> 开发者你好，由于在群聊中人数比较多，所以每次发送完指令之后，还没等添加回复语句，就有可能被别人随便发的一句话给“截胡”，不知道我这样描述你能不能听懂。
> 所以我想提一个小建议，就是只用一个语句，就完成自动回复语句的添加。例如下面这句：
> hf 你好 你好啊
> 以上的三个字符串，每个字符串之间用空格隔开，这样就能只发送一个语句就能完成添加。
> 并没有说你现在开发的哪里不好，只是感觉如果用这种方式，更加简单，快捷

**Comment by Kloping** [comment]
收到你的建议了

**Comment by Kloping** [comment]
> 开发者你好，由于在群聊中人数比较多，所以每次发送完指令之后，还没等添加回复语句，就有可能被别人随便发的一句话给“截胡”，不知道我这样描述你能不能听懂。
> 所以我想提一个小建议，就是只用一个语句，就完成自动回复语句的添加。例如下面这句：
> hf 你好 你好啊
> 以上的三个字符串，每个字符串之间用空格隔开，这样就能只发送一个语句就能完成添加。
> 并没有说你现在开发的哪里不好，只是感觉如果用这种方式，更加简单，快捷。

感谢你的建议,后续若有其他建议,欢迎提出
