### ISSUE TITLE
可以添加支持回复图片吗

### ISSUE THREAD

**Issue by verity886** [Kloping/Mirai_Plugins_Auto_Reply#2]
或者支持cq码，通过cq码发图片

**Comment by Kloping** [comment]
> 或者支持cq码，通过cq码发图片

你只的是

**Comment by Kloping** [comment]
> 或者支持cq码，通过cq码发图片

支持回复图片

**Comment by Kloping** [comment]
![image](https://user-images.githubusercontent.com/87743020/136738872-5dab37ea-b0f1-4685-a6a3-4d0092e92323.png)

**Comment by verity886** [comment]
好的，是我没仔细研究。
那另外建议加一个触发CD吧，有时候群里会复读某个命令
