### ISSUE TITLE
功能提问

### ISSUE THREAD

**Issue by cofesum** [Kloping/Mirai_Plugins_Auto_Reply#21]
请问如何添加语音回复，添加mirai码无效

**Comment by Kloping** [comment]
![image](https://user-images.githubusercontent.com/87743020/197952191-8b757a96-6d73-41b6-9506-0f4b138f222f.png)

**Comment by cofesum** [comment]
语音发完报错了
![SRKFWAYM07A2GI5I)P9 0)T](https://user-images.githubusercontent.com/108248679/197999218-e6824731-3b9f-4f15-907e-75e9d17d3f8f.png)

**Comment by Kloping** [comment]
http 插件的问题
