### ISSUE TITLE
语音回复在添加一段时间后无法正常发出

### ISSUE THREAD

**Issue by saltfish13** [Kloping/Mirai_Plugins_Auto_Reply#7]
在添加语音回且正常使用一段时间后，无法正常在移动端正常接收回复的语音消息了，但在PC端QQ可正常接收，控制台无报错
<img width="525" alt="截屏2021-12-26 下午1 06 21" src="https://user-images.githubusercontent.com/59356579/147399424-3f0814ca-507c-432d-945c-943c8f6a184f.png">
（图源Mac QQ，已在windows QQ测试过了，可以正常接收）
![DC478A66A0D063EAC57D0AB9CB594ADA](https://user-images.githubusercontent.com/59356579/147399454-bea0ffd2-14b4-4405-8c2b-82c8a99d12ea.jpg)
（图源手机QQ）

**Comment by saltfish13** [comment]
看了一下好像是从服务器获取语音消息的时候Key过期了？能不能改成把发出去的语音文件储存在本地呀

**Comment by Kloping** [comment]
mirai的问题,而且就是存在本地的

**Comment by saltfish13** [comment]
明白了
