### ISSUE TITLE
网页端乱码

### ISSUE THREAD

**Issue by shimenga** [Kloping/Mirai_Plugins_Auto_Reply#9]
![image](https://user-images.githubusercontent.com/77818664/149604729-d15ab306-801c-4f61-bec2-51de00194655.png)

**Comment by Kloping** [comment]
提供一下
- 浏览器设备 (win/mac)
- 浏览器 
- 服务器设备类型 (linux/win)

**Comment by shimenga** [comment]
win edge win

**Comment by zjy902** [comment]
同样的问题：（

**Comment by Kloping** [comment]
复现不了.jpg

尝试通过命令行设置字符集 ( -Dfile.encoding=UTF-8

**Comment by Kloping** [comment]
尝试使用新版
